import { generateMonotonicUuid } from '@lokalise/id-utils'
import { waitAndRetry } from '@lokalise/node-core'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { z } from 'zod/v4'
import { TestSuccessBackgroundJobProcessorNew } from '../../../test/processors/TestSuccessBackgroundJobProcessorNew.ts'
import { TestDependencyFactory } from '../../../test/TestDependencyFactory.ts'
import type { FakeQueueManager } from '../managers/FakeQueueManager.ts'
import type { QueueConfiguration } from '../managers/types.ts'
import { FakeBackgroundJobProcessorNew } from './FakeBackgroundJobProcessorNew.ts'
import type { BackgroundJobProcessorDependenciesNew } from './types.ts'

const supportedQueues = [
  {
    queueId: 'queue1',
    jobPayloadSchema: z.object({
      id: z.string(),
      value: z.string(),
      metadata: z.object({
        correlationId: z.string(),
      }),
    }),
  },
  {
    queueId: 'queue2',
    jobPayloadSchema: z.object({
      id: z.string(),
      value2: z.string(),
      metadata: z.object({
        correlationId: z.string(),
      }),
    }),
  },
  {
    // Dedicated queue for asserting the opt-out behaviour of the flag itself.
    queueId: 'queue3',
    purgeJobDataOnSuccess: false,
    jobPayloadSchema: z.object({
      id: z.string(),
      value2: z.string(),
      metadata: z.object({
        correlationId: z.string(),
      }),
    }),
  },
] as const satisfies QueueConfiguration[]

type SupportedQueues = typeof supportedQueues

describe('AbstractBackgroundJobProcessorNew - success', () => {
  let factory: TestDependencyFactory
  let deps: BackgroundJobProcessorDependenciesNew<SupportedQueues, 'queue1' | 'queue2'>

  let simpleProcessor: FakeBackgroundJobProcessorNew<SupportedQueues, 'queue1'>
  let processorWithSuccessHook: TestSuccessBackgroundJobProcessorNew<SupportedQueues, 'queue2'>
  let processorWithoutPurge: TestSuccessBackgroundJobProcessorNew<SupportedQueues, 'queue3'>
  let queueManager: FakeQueueManager<SupportedQueues>

  beforeEach(async () => {
    factory = new TestDependencyFactory()
    deps = factory.createNew(supportedQueues)
    queueManager = deps.queueManager

    await factory.clearRedis()

    simpleProcessor = new FakeBackgroundJobProcessorNew<SupportedQueues, 'queue1'>(deps, 'queue1')
    await simpleProcessor.start()
    processorWithSuccessHook = new TestSuccessBackgroundJobProcessorNew<SupportedQueues, 'queue2'>(
      deps,
      'queue2',
    )
    await processorWithSuccessHook.start()
    processorWithoutPurge = new TestSuccessBackgroundJobProcessorNew<SupportedQueues, 'queue3'>(
      deps,
      'queue3',
    )
    await processorWithoutPurge.start()
  })

  afterEach(async () => {
    await simpleProcessor.dispose()
    await processorWithSuccessHook.dispose()
    await processorWithoutPurge.dispose()
    await factory.dispose()
  })

  it('runs the job with autogenerated id', async () => {
    // Given
    const jobData = {
      id: generateMonotonicUuid(),
      value: 'test',
      metadata: { correlationId: generateMonotonicUuid() },
    }

    // When
    const jobId = await queueManager.schedule('queue1', jobData)

    // Then
    const UUID_REGEX =
      /^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$/
    expect(UUID_REGEX.test(jobId)).toBe(true)

    const job = await simpleProcessor.spy.waitForJobWithId(jobId, 'completed')
    expect(job.data).toMatchObject(jobData)

    const resolvedJob = await queueManager.getQueue('queue1').getJob(job.id!)
    expect(resolvedJob!.data).toStrictEqual({ metadata: jobData.metadata })

    // @ts-expect-error executing protected method for testing
    expect(simpleProcessor.worker.isRunning()).toBe(true)
  })

  it('schedules and runs multiple jobs', async () => {
    // Given - When
    const scheduledJobIds = await queueManager.scheduleBulk('queue1', [
      {
        id: generateMonotonicUuid(),
        value: 'first',
        metadata: { correlationId: generateMonotonicUuid() },
      },
      {
        id: generateMonotonicUuid(),
        value: 'second',
        metadata: { correlationId: generateMonotonicUuid() },
      },
    ])

    // Then
    expect(scheduledJobIds.length).toBe(2)

    const firstJob = await simpleProcessor.spy.waitForJobWithId(scheduledJobIds[0], 'completed')
    const secondJob = await simpleProcessor.spy.waitForJobWithId(scheduledJobIds[1], 'completed')

    expect(firstJob.data.value).toBe('first')
    expect(secondJob.data.value).toBe('second')
  })

  it('should trigger onSuccess hook', async () => {
    // Given
    const jobData = {
      id: generateMonotonicUuid(),
      value2: 'jobPayload2 test',
      metadata: { correlationId: generateMonotonicUuid() },
    }

    const jobId = await queueManager.schedule('queue2', jobData)

    const job = await processorWithSuccessHook.spy.waitForJobWithId(jobId, 'completed')
    expect(job.data).toMatchObject(jobData)

    // Then
    expect(processorWithSuccessHook.onSuccessCallsCounter).toBe(1)
  })

  it('should handle onSuccess hook error', async () => {
    const jobData = {
      id: generateMonotonicUuid(),
      value2: 'jobPayload2 test',
      metadata: { correlationId: generateMonotonicUuid() },
    }

    processorWithSuccessHook.onSuccessHook = () => {
      throw new Error('onSuccessError')
    }

    const jobId = await queueManager.schedule('queue2', jobData)

    const job = await processorWithSuccessHook.spy.waitForJobWithId(jobId, 'completed')
    expect(job.data).toMatchObject(jobData)

    // Then
    expect(processorWithSuccessHook.onSuccessCallsCounter).toBe(1)
  })

  it('purges job data on success by default', async () => {
    // Given
    const jobData = {
      id: generateMonotonicUuid(),
      value2: 'jobPayload2 test',
      metadata: { correlationId: generateMonotonicUuid() },
    }

    // When
    const jobId = await queueManager.schedule('queue2', jobData)
    await processorWithSuccessHook.spy.waitForJobWithId(jobId, 'completed')

    // Then - the onSuccess hook still saw the full data, but the persisted job is purged.
    await waitAndRetry(() => processorWithSuccessHook.runningPromisesSet.size === 0, 10, 5)
    expect(processorWithSuccessHook.runningPromisesSet).toHaveLength(0)

    expect(processorWithSuccessHook.onSuccessCallsCounter).toBe(1)
    expect(processorWithSuccessHook.jobDataResult).toStrictEqual(jobData)

    const persistedJob = await queueManager.getQueue('queue2').getJob(jobId)
    expect(persistedJob?.data).toStrictEqual({ metadata: jobData.metadata })
  })

  it('does not purge job data when purgeJobDataOnSuccess is false', async () => {
    // Given
    const jobData = {
      id: generateMonotonicUuid(),
      value2: 'jobPayload2 test',
      metadata: { correlationId: generateMonotonicUuid() },
    }

    // When
    const jobId = await queueManager.schedule('queue3', jobData)
    await processorWithoutPurge.spy.waitForJobWithId(jobId, 'completed')

    // Then - job data is preserved in full.
    await waitAndRetry(() => processorWithoutPurge.runningPromisesSet.size === 0, 10, 5)
    expect(processorWithoutPurge.runningPromisesSet).toHaveLength(0)

    expect(processorWithoutPurge.onSuccessCallsCounter).toBe(1)
    const persistedJob = await queueManager.getQueue('queue3').getJob(jobId)
    expect(persistedJob?.data).toStrictEqual(jobData)
  })

  it('ignores missing job error during automatic purging', async () => {
    // Given
    const jobData = {
      id: generateMonotonicUuid(),
      value2: 'jobPayload2 test',
      metadata: { correlationId: generateMonotonicUuid() },
    }
    // Dropping the job in the onSuccess hook
    processorWithSuccessHook.onSuccessHook = async (job) => {
      await job.remove()
    }
    const reportSpy = vi.mocked(deps.errorReporter.report)

    // When
    const jobId = await queueManager.schedule('queue2', jobData)
    await processorWithSuccessHook.spy.waitForJobWithId(jobId, 'completed')

    // Then - the purge ran and swallowed the job-missing error.
    await waitAndRetry(() => processorWithSuccessHook.runningPromisesSet.size === 0, 10, 5)
    expect(processorWithSuccessHook.runningPromisesSet).toHaveLength(0)

    expect(reportSpy).not.toHaveBeenCalled()
  })

  it('reports an error if automatic purging fails', async () => {
    // Given
    const jobData = {
      id: generateMonotonicUuid(),
      value2: 'jobPayload2 test',
      metadata: { correlationId: generateMonotonicUuid() },
    }
    // Force clearLogs to fail so the automatic purge throws.
    processorWithSuccessHook.onSuccessHook = (job) => {
      vi.spyOn(job, 'clearLogs').mockRejectedValueOnce(new Error('Simulated'))
    }
    const reportSpy = vi.mocked(deps.errorReporter.report)

    // When
    const jobId = await queueManager.schedule('queue2', jobData)
    await processorWithSuccessHook.spy.waitForJobWithId(jobId, 'completed')
    await processorWithSuccessHook.dispose()

    // Then - the purge failure is reported through the error reporter.
    expect(processorWithSuccessHook.runningPromisesSet).toHaveLength(0)
    expect(reportSpy).toHaveBeenCalledWith(
      expect.objectContaining({
        error: expect.objectContaining({
          message: expect.stringMatching(/Job data purge failed.*Simulated/),
        }),
      }),
    )
  })
})
