name: 'AI Assistance Tracking'
description: 'Validates PR descriptions for AI assistance disclosure and manages ai-assisted label'
inputs:
  github_token:
    description: 'GitHub token with pull-requests and issues write permissions'
    required: true
  pr_body:
    description: 'Pull request body content'
    required: true
  pr_number:
    description: 'Pull request number'
    required: true
  repository:
    description: 'Repository name (owner/repo)'
    required: true
  label_name:
    description: 'Label name to apply for AI-assisted PRs'
    required: false
    default: 'ai-assisted'
outputs:
  ai_assisted:
    description: 'Whether AI assisted with this PR (true/false)'
    value: ${{ steps.check_selection.outputs.ai_assisted }}
runs:
  using: "composite"
  steps:
    - name: Check AI assistance selection
      id: check_selection
      shell: bash
      env:
        PR_BODY: ${{ inputs.pr_body }}
      run: |
        # Check which checkboxes are selected
        YES_SELECTED=false
        NO_SELECTED=false

        if echo "$PR_BODY" | grep -q "\- \[x\] \*\*Yes, AI assisted with this PR\*\*"; then
          YES_SELECTED=true
        fi

        if echo "$PR_BODY" | grep -q "\- \[x\] \*\*No, AI did not assist with this PR\*\*"; then
          NO_SELECTED=true
        fi

        # Validation logic
        if [ "$YES_SELECTED" = "true" ] && [ "$NO_SELECTED" = "false" ]; then
          echo "ai_assisted=true" >> $GITHUB_OUTPUT
          echo "✅ AI assistance marked: Yes"
        elif [ "$YES_SELECTED" = "false" ] && [ "$NO_SELECTED" = "true" ]; then
          echo "ai_assisted=false" >> $GITHUB_OUTPUT
          echo "✅ AI assistance marked: No"
        elif [ "$YES_SELECTED" = "false" ] && [ "$NO_SELECTED" = "false" ]; then
          echo "❌ Error: Please select one of the AI assistance options"
          echo "ℹ️ Check the pull request template (.github/pull_request_template.md) if you're not sure how to select an option"
          exit 1
        else
          echo "❌ Error: Please select exactly one AI assistance option"
          exit 1
        fi

    - name: Add AI label
      if: steps.check_selection.outputs.ai_assisted == 'true'
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ inputs.github_token }}
        number: ${{ inputs.pr_number }}
        repo: ${{ inputs.repository }}
        labels: ${{ inputs.label_name }}

    - name: Remove AI label
      if: steps.check_selection.outputs.ai_assisted == 'false'
      uses: actions-ecosystem/action-remove-labels@v1
      with:
        github_token: ${{ inputs.github_token }}
        number: ${{ inputs.pr_number }}
        repo: ${{ inputs.repository }}
        labels: ${{ inputs.label_name }}