import { drizzle } from 'drizzle-orm/postgres-js'
import mysql from 'mysql2/promise'
import postgres from 'postgres'
import { afterAll, beforeEach, describe, expect, it } from 'vitest'
import { getDatabaseUrl } from '../test/getDatabaseUrl.ts'
import { getMysqlDatabaseUrl } from '../test/getMysqlDatabaseUrl.ts'
import { diffSchemaSnapshots } from './diffSchemaSnapshots.ts'
import type { SqlExecutor } from './markMigrationsApplied.ts'
import { snapshotSchema } from './snapshotSchema.ts'

// ──────────────────── PostgreSQL ────────────────────

describe('snapshotSchema (PostgreSQL)', () => {
  const sql = postgres(getDatabaseUrl())
  const db = drizzle({ client: sql })

  const executor: SqlExecutor = {
    run: (query: string) => sql.unsafe(query).then(() => {}),
    all: (query: string) => sql.unsafe(query) as Promise<Record<string, unknown>[]>,
  }

  const testSchemaA = 'snapshot_test_a'
  const testSchemaB = 'snapshot_test_b'

  beforeEach(async () => {
    await db.execute(`DROP SCHEMA IF EXISTS "${testSchemaA}" CASCADE`)
    await db.execute(`DROP SCHEMA IF EXISTS "${testSchemaB}" CASCADE`)
    await db.execute(`CREATE SCHEMA "${testSchemaA}"`)
    await db.execute(`CREATE SCHEMA "${testSchemaB}"`)
  })

  afterAll(async () => {
    await db.execute(`DROP SCHEMA IF EXISTS "${testSchemaA}" CASCADE`)
    await db.execute(`DROP SCHEMA IF EXISTS "${testSchemaB}" CASCADE`)
    await sql.end()
  })

  it('captures tables, columns, primary keys, foreign keys, unique constraints, indexes, enums', async () => {
    await db.execute(`CREATE TYPE "${testSchemaA}"."Color" AS ENUM ('red', 'green', 'blue')`)
    await db.execute(`
      CREATE TABLE "${testSchemaA}"."users" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "email" varchar(255) NOT NULL,
        "favorite_color" "${testSchemaA}"."Color",
        CONSTRAINT "users_email_key" UNIQUE ("email")
      )
    `)
    await db.execute(`
      CREATE TABLE "${testSchemaA}"."posts" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" integer NOT NULL,
        "title" text NOT NULL,
        "published_at" timestamp,
        CONSTRAINT "posts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "${testSchemaA}"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION
      )
    `)
    await db.execute(`CREATE INDEX "posts_user_id_idx" ON "${testSchemaA}"."posts" ("user_id")`)

    const snap = await snapshotSchema({
      executor,
      dialect: 'postgresql',
      schemas: [testSchemaA],
    })

    expect(snap.dialect).toBe('postgresql')
    const contents = snap.schemas[testSchemaA]!
    expect(Object.keys(contents.tables).sort()).toEqual(['posts', 'users'])

    const users = contents.tables.users!
    expect(users.primaryKey).toEqual({ name: 'users_pkey', columns: ['id'] })
    expect(users.columns.id).toMatchObject({
      type: 'integer',
      nullable: false,
      identity: 'by-default',
    })
    expect(users.columns.email).toMatchObject({
      type: 'character varying(255)',
      nullable: false,
    })
    expect(users.columns.favorite_color).toMatchObject({ type: `${testSchemaA}.Color` })
    expect(users.uniqueConstraints.users_email_key).toEqual({
      columns: ['email'],
      deferrable: false,
    })

    const posts = contents.tables.posts!
    expect(posts.foreignKeys.posts_user_id_fkey).toMatchObject({
      columns: ['user_id'],
      referencedSchema: testSchemaA,
      referencedTable: 'users',
      referencedColumns: ['id'],
      onDelete: 'CASCADE',
      onUpdate: 'NO ACTION',
    })
    expect(posts.indexes.posts_user_id_idx).toMatchObject({
      columns: ['user_id'],
      unique: false,
      method: 'btree',
    })

    expect(contents.enums.Color).toEqual({ values: ['red', 'green', 'blue'] })
  })

  it('captures check constraints with normalized expressions', async () => {
    await db.execute(`
      CREATE TABLE "${testSchemaA}"."products" (
        "id" integer PRIMARY KEY,
        "price" integer NOT NULL,
        CONSTRAINT "products_price_positive" CHECK ("price" > 0)
      )
    `)

    const snap = await snapshotSchema({
      executor,
      dialect: 'postgresql',
      schemas: [testSchemaA],
    })

    const products = snap.schemas[testSchemaA]!.tables.products!
    expect(products.checkConstraints.products_price_positive).toBeDefined()
    expect(products.checkConstraints.products_price_positive!.expression).toContain('price')
    expect(products.checkConstraints.products_price_positive!.expression).toContain('> 0')
  })

  it('captures sequences', async () => {
    await db.execute(`CREATE SEQUENCE "${testSchemaA}"."ticket_seq" START WITH 100 INCREMENT BY 5`)

    const snap = await snapshotSchema({
      executor,
      dialect: 'postgresql',
      schemas: [testSchemaA],
    })

    expect(snap.schemas[testSchemaA]!.sequences.ticket_seq).toMatchObject({
      start: '100',
      increment: '5',
    })
  })

  it('excludes the configured migration-tracking tables by default', async () => {
    await db.execute(`
      CREATE TABLE "${testSchemaA}"."__drizzle_migrations" ("id" serial PRIMARY KEY, "hash" text)
    `)
    await db.execute(`
      CREATE TABLE "${testSchemaA}"."_prisma_migrations" ("id" varchar(36) PRIMARY KEY)
    `)
    await db.execute(`
      CREATE TABLE "${testSchemaA}"."app_table" ("id" integer PRIMARY KEY)
    `)

    const snap = await snapshotSchema({
      executor,
      dialect: 'postgresql',
      schemas: [testSchemaA],
    })

    expect(Object.keys(snap.schemas[testSchemaA]!.tables)).toEqual(['app_table'])
  })

  it('honors a custom excludeTables list', async () => {
    await db.execute(`CREATE TABLE "${testSchemaA}"."kept" ("id" integer PRIMARY KEY)`)
    await db.execute(`CREATE TABLE "${testSchemaA}"."dropped" ("id" integer PRIMARY KEY)`)

    const snap = await snapshotSchema({
      executor,
      dialect: 'postgresql',
      schemas: [testSchemaA],
      excludeTables: ['dropped'],
    })

    expect(Object.keys(snap.schemas[testSchemaA]!.tables)).toEqual(['kept'])
  })

  it('defaults to the "public" schema when none provided', async () => {
    await db.execute(`DROP TABLE IF EXISTS "public"."snapshot_default_schema_t"`)
    await db.execute(`CREATE TABLE "public"."snapshot_default_schema_t" ("id" integer)`)

    const snap = await snapshotSchema({ executor, dialect: 'postgresql' })
    expect(snap.schemas.public).toBeDefined()
    expect(snap.schemas.public!.tables.snapshot_default_schema_t).toBeDefined()

    await db.execute(`DROP TABLE "public"."snapshot_default_schema_t"`)
  })

  it('qualifies user-defined types with their schema (cross-schema enums diff)', async () => {
    // Same enum name in two different schemas — columns referencing each must snapshot distinctly.
    await db.execute(`CREATE TYPE "${testSchemaA}"."Status" AS ENUM ('a', 'b')`)
    await db.execute(`CREATE TYPE "${testSchemaB}"."Status" AS ENUM ('a', 'b')`)
    await db.execute(`
      CREATE TABLE "${testSchemaA}"."t" ("id" integer PRIMARY KEY, "status" "${testSchemaA}"."Status")
    `)
    await db.execute(`
      CREATE TABLE "${testSchemaB}"."t" ("id" integer PRIMARY KEY, "status" "${testSchemaB}"."Status")
    `)

    const snap = await snapshotSchema({
      executor,
      dialect: 'postgresql',
      schemas: [testSchemaA, testSchemaB],
    })
    const a = snap.schemas[testSchemaA]!.tables.t!
    const b = snap.schemas[testSchemaB]!.tables.t!
    expect(a.columns.status!.type).toBe(`${testSchemaA}.Status`)
    expect(b.columns.status!.type).toBe(`${testSchemaB}.Status`)
    expect(a.columns.status!.type).not.toBe(b.columns.status!.type)
  })

  it('captures fractional-seconds precision for time/timestamp/interval columns', async () => {
    await db.execute(`
      CREATE TABLE "${testSchemaA}"."precision_t" (
        "id" integer PRIMARY KEY,
        "ts3" timestamp(3),
        "ts6" timestamp(6),
        "tsz0" timestamp(0) with time zone,
        "t2" time(2),
        "ivl" interval(4)
      )
    `)

    const snap = await snapshotSchema({
      executor,
      dialect: 'postgresql',
      schemas: [testSchemaA],
    })
    const cols = snap.schemas[testSchemaA]!.tables.precision_t!.columns
    expect(cols.ts3!.type).toBe('timestamp(3) without time zone')
    expect(cols.ts6!.type).toBe('timestamp(6) without time zone')
    expect(cols.tsz0!.type).toBe('timestamp(0) with time zone')
    expect(cols.t2!.type).toBe('time(2) without time zone')
    expect(cols.ivl!.type).toMatch(/^interval\(4\)/)
    // Differing precision must surface as a diff, not be silently equal.
    expect(cols.ts3!.type).not.toBe(cols.ts6!.type)
  })

  // ──────── End-to-end "Prisma vs Drizzle" conformance scenarios ────────

  it('e2e: identical schema built via two DDL paths produces equal snapshots', async () => {
    // Build the "Prisma-style" schema in schemaA with explicit names
    await db.execute(`
      CREATE TABLE "${testSchemaA}"."User" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY,
        "email" varchar(255) NOT NULL,
        CONSTRAINT "User_pkey" PRIMARY KEY ("id"),
        CONSTRAINT "User_email_key" UNIQUE ("email")
      )
    `)

    // Build the "Drizzle-style" schema in schemaB with the SAME explicit names
    await db.execute(`
      CREATE TABLE "${testSchemaB}"."User" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY,
        "email" varchar(255) NOT NULL,
        CONSTRAINT "User_pkey" PRIMARY KEY ("id"),
        CONSTRAINT "User_email_key" UNIQUE ("email")
      )
    `)

    const a = await snapshotSchema({ executor, dialect: 'postgresql', schemas: [testSchemaA] })
    const b = await snapshotSchema({ executor, dialect: 'postgresql', schemas: [testSchemaB] })

    // Normalize the schema key so we can diff cross-schema
    const aNorm = { ...a, schemas: { common: a.schemas[testSchemaA]! } }
    const bNorm = { ...b, schemas: { common: b.schemas[testSchemaB]! } }
    const diff = diffSchemaSnapshots(aNorm, bNorm)
    expect(diff.equal).toBe(true)
  })

  it('e2e: mismatched constraint names surface as a diff (real defect in Drizzle schema)', async () => {
    // schemaA: Prisma-style names
    await db.execute(`
      CREATE TABLE "${testSchemaA}"."User" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY,
        "email" varchar(255) NOT NULL,
        CONSTRAINT "User_pkey" PRIMARY KEY ("id"),
        CONSTRAINT "User_email_key" UNIQUE ("email")
      )
    `)

    // schemaB: Drizzle-default names (user forgot the explicit overrides)
    await db.execute(`
      CREATE TABLE "${testSchemaB}"."User" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY,
        "email" varchar(255) NOT NULL,
        CONSTRAINT "user_pkey" PRIMARY KEY ("id"),
        CONSTRAINT "user_email_unique" UNIQUE ("email")
      )
    `)

    const a = await snapshotSchema({ executor, dialect: 'postgresql', schemas: [testSchemaA] })
    const b = await snapshotSchema({ executor, dialect: 'postgresql', schemas: [testSchemaB] })

    const aNorm = { ...a, schemas: { common: a.schemas[testSchemaA]! } }
    const bNorm = { ...b, schemas: { common: b.schemas[testSchemaB]! } }
    const diff = diffSchemaSnapshots(aNorm, bNorm)
    expect(diff.equal).toBe(false)

    // The PK name change manifests at the primaryKey.name path.
    expect(
      diff.differences.some(
        (d) =>
          d.path === 'schemas.common.tables.User.primaryKey.name' &&
          d.before === 'User_pkey' &&
          d.after === 'user_pkey',
      ),
    ).toBe(true)

    // The unique constraint rename surfaces as add+remove since the key in the map changed.
    expect(
      diff.differences.some(
        (d) => d.path.endsWith('uniqueConstraints.User_email_key') && d.kind === 'removed',
      ),
    ).toBe(true)
    expect(
      diff.differences.some(
        (d) => d.path.endsWith('uniqueConstraints.user_email_unique') && d.kind === 'added',
      ),
    ).toBe(true)
  })

  it('e2e: SERIAL vs IDENTITY surfaces as a diff (semantic schema change)', async () => {
    await db.execute(`
      CREATE TABLE "${testSchemaA}"."T" (
        "id" serial PRIMARY KEY
      )
    `)
    await db.execute(`
      CREATE TABLE "${testSchemaB}"."T" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
      )
    `)

    const a = await snapshotSchema({ executor, dialect: 'postgresql', schemas: [testSchemaA] })
    const b = await snapshotSchema({ executor, dialect: 'postgresql', schemas: [testSchemaB] })

    const aNorm = { ...a, schemas: { common: a.schemas[testSchemaA]! } }
    const bNorm = { ...b, schemas: { common: b.schemas[testSchemaB]! } }
    const diff = diffSchemaSnapshots(aNorm, bNorm)
    expect(diff.equal).toBe(false)
    // Serial → column default = nextval(...); identity → no default but identity = 'by-default'
    const paths = diff.differences.map((d) => d.path)
    expect(paths).toContain('schemas.common.tables.T.columns.id.default')
    expect(paths).toContain('schemas.common.tables.T.columns.id.identity')
    // schemaA has a sequence (from serial), schemaB does not — surfaces as an added/removed sequence
    expect(
      diff.differences.some(
        (d) => d.path === 'schemas.common.sequences.T_id_seq' && d.kind === 'removed',
      ),
    ).toBe(true)
  })
})

// ──────────────────── MySQL ────────────────────

describe('snapshotSchema (MySQL)', () => {
  const pool = mysql.createPool(getMysqlDatabaseUrl())

  const executor: SqlExecutor = {
    run: (query: string) => pool.execute(query).then(() => {}),
    all: (query: string) => pool.execute(query).then(([rows]) => rows as Record<string, unknown>[]),
  }

  beforeEach(async () => {
    await pool.execute('DROP TABLE IF EXISTS `snapshot_posts`')
    await pool.execute('DROP TABLE IF EXISTS `snapshot_users`')
    await pool.execute('DROP TABLE IF EXISTS `snapshot_products`')
    await pool.execute('DROP TABLE IF EXISTS `__drizzle_migrations`')
    await pool.execute('DROP TABLE IF EXISTS `_prisma_migrations`')
    await pool.execute('DROP TABLE IF EXISTS `snapshot_kept`')
    await pool.execute('DROP TABLE IF EXISTS `snapshot_dropped`')
    await pool.execute('DROP TABLE IF EXISTS `snapshot_T_a`')
    await pool.execute('DROP TABLE IF EXISTS `snapshot_T_b`')
    await pool.execute('DROP TABLE IF EXISTS `snapshot_T_a_named`')
    await pool.execute('DROP TABLE IF EXISTS `snapshot_T_b_named`')
  })

  afterAll(async () => {
    await pool.execute('DROP TABLE IF EXISTS `snapshot_posts`')
    await pool.execute('DROP TABLE IF EXISTS `snapshot_users`')
    await pool.execute('DROP TABLE IF EXISTS `snapshot_products`')
    await pool.execute('DROP TABLE IF EXISTS `__drizzle_migrations`')
    await pool.execute('DROP TABLE IF EXISTS `_prisma_migrations`')
    await pool.execute('DROP TABLE IF EXISTS `snapshot_kept`')
    await pool.execute('DROP TABLE IF EXISTS `snapshot_dropped`')
    await pool.execute('DROP TABLE IF EXISTS `snapshot_T_a`')
    await pool.execute('DROP TABLE IF EXISTS `snapshot_T_b`')
    await pool.execute('DROP TABLE IF EXISTS `snapshot_T_a_named`')
    await pool.execute('DROP TABLE IF EXISTS `snapshot_T_b_named`')
    await pool.end()
  })

  it('captures tables, columns, primary keys, foreign keys, unique constraints, indexes', async () => {
    await pool.execute(`
      CREATE TABLE \`snapshot_users\` (
        \`id\` int NOT NULL AUTO_INCREMENT,
        \`email\` varchar(255) NOT NULL,
        \`name\` varchar(100),
        PRIMARY KEY (\`id\`),
        UNIQUE KEY \`snapshot_users_email_key\` (\`email\`)
      )
    `)
    await pool.execute(`
      CREATE TABLE \`snapshot_posts\` (
        \`id\` int NOT NULL AUTO_INCREMENT,
        \`user_id\` int NOT NULL,
        \`title\` varchar(200) NOT NULL,
        PRIMARY KEY (\`id\`),
        KEY \`snapshot_posts_user_id_idx\` (\`user_id\`),
        CONSTRAINT \`snapshot_posts_user_id_fkey\` FOREIGN KEY (\`user_id\`) REFERENCES \`snapshot_users\` (\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION
      )
    `)

    const snap = await snapshotSchema({ executor, dialect: 'mysql' })

    expect(snap.dialect).toBe('mysql')
    const dbName = Object.keys(snap.schemas)[0]!
    const contents = snap.schemas[dbName]!
    expect(contents.tables.snapshot_users).toBeDefined()
    expect(contents.tables.snapshot_posts).toBeDefined()

    const users = contents.tables.snapshot_users!
    expect(users.primaryKey).toEqual({ name: 'PRIMARY', columns: ['id'] })
    expect(users.columns.id).toMatchObject({
      type: 'int',
      nullable: false,
      extra: 'auto_increment',
    })
    expect(users.columns.email).toMatchObject({
      type: 'varchar(255)',
      nullable: false,
    })
    expect(users.uniqueConstraints.snapshot_users_email_key).toMatchObject({
      columns: ['email'],
    })

    const posts = contents.tables.snapshot_posts!
    expect(posts.foreignKeys.snapshot_posts_user_id_fkey).toMatchObject({
      columns: ['user_id'],
      referencedTable: 'snapshot_users',
      referencedColumns: ['id'],
      onDelete: 'CASCADE',
      onUpdate: 'NO ACTION',
    })
    expect(posts.indexes.snapshot_posts_user_id_idx).toMatchObject({
      columns: ['user_id'],
      unique: false,
    })
  })

  it('captures check constraints when supported', async () => {
    await pool.execute(`
      CREATE TABLE \`snapshot_products\` (
        \`id\` int NOT NULL PRIMARY KEY,
        \`price\` int NOT NULL,
        CONSTRAINT \`snapshot_products_price_positive\` CHECK (\`price\` > 0)
      )
    `)

    const snap = await snapshotSchema({ executor, dialect: 'mysql' })
    const dbName = Object.keys(snap.schemas)[0]!
    const products = snap.schemas[dbName]!.tables.snapshot_products!
    // MySQL 8.0+ — check constraints captured. Earlier versions silently skip.
    if (products.checkConstraints.snapshot_products_price_positive) {
      expect(products.checkConstraints.snapshot_products_price_positive.expression).toContain(
        'price',
      )
    }
  })

  it('excludes default migration-tracking tables', async () => {
    await pool.execute(`
      CREATE TABLE \`__drizzle_migrations\` (\`id\` int PRIMARY KEY)
    `)
    await pool.execute(`
      CREATE TABLE \`_prisma_migrations\` (\`id\` varchar(36) PRIMARY KEY)
    `)
    await pool.execute(`
      CREATE TABLE \`snapshot_kept\` (\`id\` int PRIMARY KEY)
    `)

    const snap = await snapshotSchema({ executor, dialect: 'mysql' })
    const dbName = Object.keys(snap.schemas)[0]!
    const names = Object.keys(snap.schemas[dbName]!.tables)
    expect(names).toContain('snapshot_kept')
    expect(names).not.toContain('__drizzle_migrations')
    expect(names).not.toContain('_prisma_migrations')
  })

  it('honors a custom excludeTables list', async () => {
    await pool.execute(`CREATE TABLE \`snapshot_kept\` (\`id\` int PRIMARY KEY)`)
    await pool.execute(`CREATE TABLE \`snapshot_dropped\` (\`id\` int PRIMARY KEY)`)

    const snap = await snapshotSchema({
      executor,
      dialect: 'mysql',
      excludeTables: ['snapshot_dropped'],
    })
    const dbName = Object.keys(snap.schemas)[0]!
    const names = Object.keys(snap.schemas[dbName]!.tables)
    expect(names).toContain('snapshot_kept')
    expect(names).not.toContain('snapshot_dropped')
  })

  it('e2e: identical schema built twice produces equal snapshots', async () => {
    await pool.execute(`
      CREATE TABLE \`snapshot_T_a\` (
        \`id\` int NOT NULL AUTO_INCREMENT,
        \`email\` varchar(255) NOT NULL,
        PRIMARY KEY (\`id\`),
        UNIQUE KEY \`snapshot_T_email_key\` (\`email\`)
      )
    `)
    await pool.execute(`
      CREATE TABLE \`snapshot_T_b\` (
        \`id\` int NOT NULL AUTO_INCREMENT,
        \`email\` varchar(255) NOT NULL,
        PRIMARY KEY (\`id\`),
        UNIQUE KEY \`snapshot_T_email_key\` (\`email\`)
      )
    `)

    const snap = await snapshotSchema({
      executor,
      dialect: 'mysql',
      excludeTables: [
        '__drizzle_migrations',
        '_prisma_migrations',
        'snapshot_T_b',
        'snapshot_users',
        'snapshot_posts',
        'snapshot_products',
        'snapshot_kept',
        'snapshot_dropped',
      ],
    })

    // Get the snapshot_T_a table
    const dbName = Object.keys(snap.schemas)[0]!
    const tableA = snap.schemas[dbName]!.tables.snapshot_T_a!

    // Snapshot just snapshot_T_b
    const snap2 = await snapshotSchema({
      executor,
      dialect: 'mysql',
      excludeTables: [
        '__drizzle_migrations',
        '_prisma_migrations',
        'snapshot_T_a',
        'snapshot_users',
        'snapshot_posts',
        'snapshot_products',
        'snapshot_kept',
        'snapshot_dropped',
      ],
    })
    const tableB = snap2.schemas[dbName]!.tables.snapshot_T_b!

    // Strip the per-table name from the unique key path by renaming consistently
    expect(tableA.columns).toEqual(tableB.columns)
    expect(tableA.primaryKey).toEqual(tableB.primaryKey)
    expect(tableA.uniqueConstraints).toEqual(tableB.uniqueConstraints)
  })

  it('e2e: mismatched index name surfaces as a diff (real defect in Drizzle schema)', async () => {
    await pool.execute(`
      CREATE TABLE \`snapshot_T_a_named\` (
        \`id\` int NOT NULL AUTO_INCREMENT,
        \`email\` varchar(255) NOT NULL,
        PRIMARY KEY (\`id\`),
        UNIQUE KEY \`Prisma_style_email_key\` (\`email\`)
      )
    `)
    await pool.execute(`
      CREATE TABLE \`snapshot_T_b_named\` (
        \`id\` int NOT NULL AUTO_INCREMENT,
        \`email\` varchar(255) NOT NULL,
        PRIMARY KEY (\`id\`),
        UNIQUE KEY \`drizzle_style_email_unique\` (\`email\`)
      )
    `)

    const snap = await snapshotSchema({ executor, dialect: 'mysql' })
    const dbName = Object.keys(snap.schemas)[0]!
    const a = snap.schemas[dbName]!.tables.snapshot_T_a_named!
    const b = snap.schemas[dbName]!.tables.snapshot_T_b_named!

    expect(Object.keys(a.uniqueConstraints)).toEqual(['Prisma_style_email_key'])
    expect(Object.keys(b.uniqueConstraints)).toEqual(['drizzle_style_email_unique'])
    // The structural names diverge — exactly the signal we want to catch.
  })
})
