name: Package release to NPM -> tsconfig
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'packages/dev/tsconfig/**'

jobs:
  call-build-flow:
    uses: lokalise/shared-ts-libs/.github/workflows/release.package.yml@main
    with:
      working_directory: 'packages/dev/tsconfig'
      package_name: '@lokalise/tsconfig'
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
