name: Package release to NPM -> context-plugins
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'packages/app/context-plugins/**'

jobs:
  call-build-flow:
    uses: lokalise/shared-ts-libs/.github/workflows/release.package.yml@main
    with:
      working_directory: 'packages/app/context-plugins'
      package_name: 'context-fastify-plugins'
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
