name: Package release to NPM -> error-utils
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'packages/app/error-utils/**'

jobs:
  call-build-flow:
    uses: lokalise/shared-ts-libs/.github/workflows/release.package.yml@main
    with:
      working_directory: 'packages/app/error-utils'
      package_name: 'error-utils'
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
