name: Package release to NPM -> backend-http-client
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'packages/app/backend-http-client/**'

jobs:
  call-build-flow:
    uses: lokalise/shared-ts-libs/.github/workflows/release.package.yml@main
    with:
      working_directory: 'packages/app/backend-http-client'
      package_name: 'backend-http-client'
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
