name: Package release to NPM -> websockets-common
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'packages/app/websockets-common/**'

jobs:
  call-build-flow:
    uses: lokalise/shared-ts-libs/.github/workflows/release.package.yml@main
    with:
      working_directory: 'packages/app/websockets-common'
      package_name: 'websockets-common'
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
